spring.application.name=biblioteca
spring.data.jpa.repositories.bootstrap-mode=default
spring.datasource.url=jdbc:postgresql://localhost:5432/livraria
spring.datasource.username=postgres
spring.datasource.password=sambm1409
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

